window:
  dimensions:
   columns: 150
   lines: 40
  position:
   x: 0
   y: 0
  padding:
   x: 5
   y: 0
  dynamic_padding: true
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: none
  opacity: 0.9
  Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  startup_mode: Windowed
  # Window title
  title: Alacritty
  dynamic_title: true
  Window class (Linux/BSD only):
  class:
    instance: Alacritty
    general: Alacritty
  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark`
  # and `light`. Set this to `None` to use the default theme variant.
  gtk_theme_variant: None

scrolling:
  history: 10000
  multiplier: 3
  # background_opacity: 0.5
  live_config_reload: true


##########################################    DRACULA  ###############  

schemes:
  # Default colors
  dracula: &dracula
    primary:
      # background: '#282a36'
      background: '#141414'
      foreground: '#f8f8f2'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'

    # Bright colors
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'

###########################################     GRUVBOX   ############

schemes:
 # Default colors
  gruvbox: &gruvbox
    primary:
      background: '#1d2021'
      # background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'
     # Normal colors
    normal:
      black:   '#282828'
      red:     '#fb4934'
      green:   '#90ee90'
      yellow:  '#fabd2f'
      blue:    '#458588'
      magenta: '#b16286' 
      cyan:    '#8ec07c'
      white:   '#D3D3D3'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

###########################################    Tokyo Night   ############
schemes:
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '#141414'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#7aa2f7'
      white:   '#787c99'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  tokyo-night-storm: &tokyo-night-storm
      # Default colors
      primary:
        background: '#24283b'
        foreground: '#a9b1d6'

      # Normal colors
      normal:
        black:   '#32344a'
        red:     '#f7768e'
        green:   '#9ece6a'
        yellow:  '#e0af68'
        blue:    '#7aa2f7'
        magenta: '#ad8ee6'
        cyan:    '#449dab'
        white:   '#9699a8'

      # Bright colors
      bright:
        black:   '#444b6a'
        red:     '#ff7a93'
        green:   '#b9f27c'
        yellow:  '#ff9e64'
        blue:    '#7da6ff'
        magenta: '#bb9af7'
        cyan:    '#0db9d7'
        white:   '#acb0d0'

###########################################    Monokai-pro   ############
schemes:
  monokai-pro: &monokai-pro
    # Default colors
    primary:
      background: '#2d2a2e'
      foreground: '#fcfcfa'

    # Normal colors
    normal:
      black:   '#221f22'
      red:     '#ff6188'
      green:   '#a9dc76'
      yellow:  '#ffd866'
      blue:    '#fc9867'
      magenta: '#ab9df2'
      cyan:    '#78dce8'
      white:   '#fcfcfa'

    # Bright colors
    bright:
      black:   '#221f22'
      red:     '#ff6188'
      green:   '#a9dc76'
      yellow:  '#ffd866'
      blue:    '#fc9867'
      magenta: '#ab9df2'
      cyan:    '#78dce8'
      white:   '#fcfcfa'

###################################### Set Theme #####################################
colors: *dracula

###############################################      cursor      ##############################################
################################################################# Font configuration
font:
  normal:
    family: Cascadia Code
    style: Medium
  bold:
    family: Cascadia Code
    style: Bold
  italic:
    family: Cascadia Code
    style: Italic
  bold_italic:
    family: Cascadia Code
    style: Bold Italic

# font:
#   normal:
#     family: Operator Mono Lig
#     style: Regular
#   bold:
#     family: Operator Mono SSm Lig Book
#     style: Bold
#   italic:
#     family: Operator Mono
#     style: Italic
#   bold_italic:
#     family: Operator Mono Lig
#     style: Bold Italic

  # Point size
  size: 8

  offset:
   x: 0
   y: 3
  glyph_offset:
   x: 0
   y: 0

cursor:
  style:
    Values for `shape`:
    #   - â–‡ Block
    #   - _ Underline
    #   - | Beam
    shape: Block
    Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Off
